//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using ScreenFIRE.Assets;
using Material.Icons;
using System.Security.Cryptography;
using System.Configuration;
namespace ScreenFIRE.Modules.Companion {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Cache : ApplicationSettingsBase {

        private static Cache defaultInstance = ((Cache)(ApplicationSettingsBase.Synchronized(new Cache())));

        public static Cache Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dictionary<MaterialIconKind, string> MaterialIcons {
            get {
                return ((Dictionary<MaterialIconKind, string>)(this["MaterialIcons"]));
            }
            set {
                this["MaterialIcons"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dictionary<ILanguages, Dictionary<Assets.IStrings, string>> StringsStore {
            get {
                return ((Dictionary<ILanguages, Dictionary<IStrings, string>>)(this["StringsStore"]));
            }
            set {
                this["StringsStore"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Aes LastAes {
            get {
                return ((Aes)(this["LastAes"]));
            }
            set {
                this["LastAes"] = value;
            }
        }
    }
}
