//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ScreenFIRE.Assets;
using ScreenFIRE.Modules.Companion.Status;
using System.Collections.Generic;

namespace ScreenFIRE.Modules.Companion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Cache : global::System.Configuration.ApplicationSettingsBase {
        
        private static Cache defaultInstance = ((Cache)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Cache())));
        
        public static Cache Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.Dictionary<Material.Icons.MaterialIconKind,string> MaterialIcons {
            get {
                return ((global::System.Collections.Generic.Dictionary<Material.Icons.MaterialIconKind, string>)(this["MaterialIcons"]));
            }
            set {
                this["MaterialIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dictionary<ILanguages, Dictionary<IStrings, string>> StringsStore {
            get {
                return ((Dictionary<ILanguages, Dictionary<IStrings, string>>)(this["StringsStore"]));
            }
            set {
                this["StringsStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Security.Cryptography.Aes LastAes {
            get {
                return ((global::System.Security.Cryptography.Aes)(this["LastAes"]));
            }
            set {
                this["LastAes"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public List<Objective> ObjectiveHistory {
            get {
                return ((List<Objective>)(this["ObjectiveHistory"]));
            }
            set {
                this["ObjectiveHistory"] = value;
            }
        }
    }
}
